### ISSUE TITLE
Sort out Research Data Storage for the project

### ISSUE THREAD

**Issue by raquel-ucl** [UCL-PACE/AX3-temp-output#3]
@KennardGit has to talk to his PI to request some space using this form below:

https://utilities.rd.ucl.ac.uk/register

**Comment by KennardGit** [comment]
The request has been logged, I'll close this thread once it's finalised

Thank you for your registration for your project:
AX3-Temp-output
Your storage is being allocated on the RDS iRODS infrastructure.
Your project ID is:

rd00f9

**Comment by raquel-ucl** [comment]
@KennardGit I was surprised about the email you got from RDS mentioning iRODS infrastructure, so I've asked one of the RDS people since they sit opposite me. 

They can't offer GPFS (the standard file storage system where you can just SSH to and easily copy data back and forth) right now because of installation problems on the new data centre. They will offer this option to researchers, but maybe not until October - it's hard to tell when all will be fixed and ready. 

In the meanwhile we can use iRODS, which is not ideal but should be OK as a temporary solution to store your data and share it with us. In order to access iRODS from your laptop, you'll need to install a tool called Cyberduck and follow the instructions RDS prepared [here](http://www.ucl.ac.uk/isd/services/research-it/research-data/storage/access-guide/rds-irods-access).

They claim to have some GPFS space for emergencies which we could request if you find iRODS too tedious. Let us know and we'll speak to them. In the meanwhile, please have a go with Cyberduck and move the 10-day file there, so we can access it. Give a shout if you need help with that.

**Comment by raquel-ucl** [comment]
This has already been done. We'll be using iRODS for now until there is a new GPFS we can migrate the data to. Stuart, me and the team's bot have been given access to it, so closing.
